### PR TITLE
Prettify the code

### PR DESCRIPTION
**Pull request by ArjixWasTaken**
Some small, but imo important, code style improvements.

PS: Why did you do `[...document.querySelectorAll('xyz')][0]` instead of `document.querySelector('xyz')`?

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
Warning: I have not tested the code, this was directly written using GitHub's file editor.

**Comment by Yaw-Dev** [comment]
the code seems to be working fine, thanks for the contribution.
the reason why I did `[...document.querySelectorAll('xyz')][0]` is simply that I'm new to JS and was trying a few different things out.
I had a lot of help on this project by a friend (especially on the gui side of things)

**Comment by ArjixWasTaken** [comment]
> the reason why I did `[...document.querySelectorAll('xyz')][0]` is simply that I'm new to JS and was trying a few different things out.

Naruhodo, in that case feel free to DM me on discord if you have any questions or need help coding!

(PS: Και 'γω Έλληνας είμαι)

**Comment by Yaw-Dev** [comment]
> > the reason why I did `[...document.querySelectorAll('xyz')][0]` is simply that I'm new to JS and was trying a few different things out.
> 
> Naruhodo, in that case feel free to DM me on discord if you have any questions or need help coding!
> 
> (PS: Και 'γω Έλληνας είμαι)

Ναι το προσεξα πριν λίγο, ευχαριστω για την βοηθεια.

**Pull request merged**
